CREATE FULLTEXT CATALOG ft AS DEFAULT
CREATE UNIQUE INDEX ui_rec_name ON dbo.Recipes(Id);
CREATE FULLTEXT INDEX ON dbo.Recipes( Recipes TYPE COLUMN Name Language 1049) KEY INDEX ui_rec_name ON(ft) WITH CHANGE_TRACKING AUTO